name: Release

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  GOOS: linux
  GOARCH: arm64
  ZIP_FILE: ticker.zip

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build and zip
        run: ./scripts/build_and_zip.sh

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$(date +'%Y.%m.%d.%H.%M.%S')" \
            '${{ env.ZIP_FILE }}' \
            --latest
