name: Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build and zip
        run: ./scripts/build_and_zip.sh

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$(date +'%Y.%m.%d.%H.%M.%S')" \
            bootstrap.zip \
            --latest
